- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install gh
    package:
      name: gh

  - name: gitconfig
    copy:
      src: files/gitconfig
      dest: $HOME/.gitconfig"
      remote_src: yes
