- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install gh
    package:
      name: gh

  - name: gitconfig
    copy:
      src: "{{ item }}"
      dest: "$HOME/{{ item }}"
    loop:
      - .gitconfig
