- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: home dir
    shell: "echo $HOME"
    register: home_dir
    changed_when: false
    check_mode: no

  - name: debug home dir
    debug: ver=home_dir

  - name: install gh
    package:
      name: gh

  - name: gitconfig
    copy:
      src: files/gitconfig
      dest: "{{ home_dir }}/.gitconfig"
      remote_src: yes
